export { default as close } from "./close.png";
export { default as favorites } from "./favorites.png";
export { default as haveRead } from "./have-read.png";
export { default as info } from "./info.png";
export { default as noResults } from "./no-results.png";
export { default as readingNow } from "./reading-now.png";
export { default as search } from "./search.png";
export { default as toRead } from "./to-read.png";
export { default as userIcon } from "./user.png";
